// SPDX-License-Identifier: LicenseRef-tokenstat-source-available
//
// Source-available for review, NOT open source. See LICENSE: no rights to
// redistribute, publish, or ship a build are granted.
//
// "tokenstat" and the tokenstat marks are trademarks of pueev OU and are not
// licensed with the code. See TRADEMARK.md.

//! Refreshing the list-rate price book, and keeping a session's cached copy in
//! step.
//!
//! Reports price against the book the session opened with, because re-reading
//! it per frame is what the interactive CLI did before this was a cache. A
//! long-lived daemon therefore has to reload the cached copy after a refresh,
//! or every report keeps pricing against the empty (or yesterday's) book until
//! the process restarts — which is exactly what a machine without the CLI saw:
//! the daemon fetched a book it never used.

use tokenstat_core::PriceTable;

use crate::session::Session;

/// Replace a session's cached book with what is on disk.
///
/// Called after a successful refresh. Cheap enough for the hourly cadence: one
/// read and one parse of the snapshot file, and the catalog behind it is
/// shared, not re-read per report.
pub fn reload(session: &mut Session) {
    session.prices = PriceTable::load_with_catalog();
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;
    use std::sync::atomic::{AtomicU64, Ordering};

    use super::*;
    use crate::session::OpenParams;

    /// The data directory follows `$HOME` on macOS (via the `directories`
    /// crate), so the reload test points it at a temp dir. `HOME` is
    /// process-wide, so tests that repoint it must not run at the same time;
    /// this lock is the same convention the identity tests use.
    static HOME_LOCK: Mutex<()> = Mutex::new(());
    static SEQ: AtomicU64 = AtomicU64::new(0);

    const SNAPSHOT: &str = r#"{
      "effective_from": "2026-08-01",
      "note": "List-rate snapshot generated by tokenstat.ai.",
      "models": [{
        "match": "example/model",
        "input": 3.0,
        "output": 15.0,
        "cache_read": 0.3,
        "cache_write_5m": 3.75,
        "cache_write_1h": 0.0
      }]
    }"#;

    struct HomeGuard(Option<std::ffi::OsString>);

    impl Drop for HomeGuard {
        fn drop(&mut self) {
            match &self.0 {
                Some(home) => unsafe { std::env::set_var("HOME", home) },
                None => unsafe { std::env::remove_var("HOME") },
            }
        }
    }

    fn temp_home() -> (std::path::PathBuf, HomeGuard) {
        let previous = std::env::var_os("HOME");
        let home = std::env::temp_dir().join(format!(
            "tokenstat-pricing-home-{}-{}",
            std::process::id(),
            SEQ.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&home).unwrap();
        unsafe { std::env::set_var("HOME", &home) };
        (home, HomeGuard(previous))
    }

    #[test]
    fn a_refreshed_book_replaces_the_cached_one() {
        let _guard = HOME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (home, _restore) = temp_home();

        // A snapshot on disk, as `pricing.refresh` would have written it.
        let book = PriceTable::default_path().expect("data directory");
        std::fs::create_dir_all(book.parent().unwrap()).unwrap();
        std::fs::write(&book, SNAPSHOT).unwrap();

        let dir = home.join("session");
        std::fs::create_dir_all(&dir).unwrap();
        let mut session = Session::open(&OpenParams {
            db_path: Some(dir.join("tokenstat.db").display().to_string()),
            timezone: Some("UTC".into()),
        })
        .expect("open temp archive");

        // A daemon that started before its first fetch holds the empty book,
        // which is the machine the bug report describes. The refresh writes
        // the file; the session has to be told about it.
        session.prices = PriceTable::default();
        assert!(
            session.prices.is_empty(),
            "precondition: session is unpriced"
        );

        reload(&mut session);

        assert!(!session.prices.is_empty(), "reload must pick up the book");
        assert_eq!(session.prices.effective_from, "2026-08-01");
        assert_eq!(
            session.prices.get_exact("example/model").map(|r| r.input),
            Some(3.0)
        );
    }
}
